### PR TITLE
Add custom method to calculate references

### LINKED ISSUE #40: Use resource id to calculate reference
# This is a Feature Proposal

#### :tophat: Description

Resources references must use a custom method to render just the resource id instead of the default one:

image

#### :pushpin: Related issues
None

#### :clipboard: Additional Data
N/A

### PR DESCRIPTION
**Pull request by beagleknight**
#### :tophat: What? Why?

This adds a custom method to calculate references using the resource id.

The references must be deleted in order to recalculate the new ones.

#### :pushpin: Related Issues
- Closes #40 

#### :clipboard: Subtasks
None

### :camera: Screenshots (optional)
image

#### :ghost: GIF
None

### CODE REVIEW

**Comment by mrcasals** [comment]
Won't this make things with the same reference ID? Eg a proposal and a meeting would have the same reference :/

**Comment by beagleknight** [comment]
Ping @oriolgual

**Comment by oriolgual** [comment]
That's true @mrcasals, can we add a prefix for the resource type? Like `PROP-73`

**Comment by beagleknight** [comment]
@mrcasals @oriolgual Added resource prefix

**Pull request merged**
